### ISSUE TITLE
Bring up robot checklist

### ISSUE THREAD

**Issue by huyha23** [Manchester-Central/2023-Charged-Up#85]
- [x] Swerve Drive
  - [x] Confirm ports for absolute encoders map to same modules
  - [x] Confirm all TalonFX are still in the same position.
  - [x] #62 
    - [x] Confirm max module velocity.
- [x] Arm
  - [x] Assign up ID and firmware for the SparkMaxes.
  - [x] Confirm Sensor readout.
    - [x] Ensure angle meet our expectation.
  - [x] #70 
  - [x] #68

**Comment by huyha23** [comment]
Basic Bring up is done. Adding Scoring position.
